export const data = [
    {
        "SNo":1,
        "State":"Andhra Pradesh",
        "Type":"State University",
        "Yrofestab":1964,
        "Name":"Acharya N.G. Ranga Agricultural University, Lam, Guntur – 522 034,Andhra Pradesh (State University)",
        "Name_1":"Acharya N.G. Ranga Agricultural University",
        "Village ":"Lam",
        "City":"Guntur",
        "District":"Dt. Guntur",
        "PIN":522034,
        "url":"https://angrau.ac.in/",
        "Phone":"0863-2347102",
        "Email":"registrar@angrau.ac.in",
        "location coordinates":18004250430,
        "Image":"https://angrau.ac.in/Images/hmsl1.jpg",
        "Logo":"https://factstranscript.com/wp-content/uploads/2020/07/Acharaya-N.G.Ranga-Agricultural-University.png"
    },
    {
        "SNo":1,
        "State":"Andhra Pradesh",
        "Type":"State University",
        "Yrofestab":1964,
        "Name":"Acharya N.G. Ranga Agricultural University, Lam, Guntur – 522 034,Andhra Pradesh (State University)",
        "Name_1":"Acharya N.G. Ranga Agricultural University",
        "Village ":"Lam",
        "City":"Guntur",
        "District":"Dt. Guntur",
        "PIN":522034,
        "url":"https://angrau.ac.in/",
        "Phone":"0863-2347102",
        "Email":"registrar@angrau.ac.in",
        "location coordinates":18004250430,
        "Image":"https://angrau.ac.in/Images/hmsl1.jpg",
        "Logo":"https://factstranscript.com/wp-content/uploads/2020/07/Acharaya-N.G.Ranga-Agricultural-University.png"
    },
    {
        "SNo":1,
        "State":"Andhra Pradesh",
        "Type":"State University",
        "Yrofestab":1964,
        "Name":"Acharya N.G. Ranga Agricultural University, Lam, Guntur – 522 034,Andhra Pradesh (State University)",
        "Name_1":"Acharya N.G. Ranga Agricultural University",
        "Village ":"Lam",
        "City":"Guntur",
        "District":"Dt. Guntur",
        "PIN":522034,
        "url":"https://angrau.ac.in/",
        "Phone":"0863-2347102",
        "Email":"registrar@angrau.ac.in",
        "location coordinates":18004250430,
        "Image":"https://angrau.ac.in/Images/hmsl1.jpg",
        "Logo":"https://factstranscript.com/wp-content/uploads/2020/07/Acharaya-N.G.Ranga-Agricultural-University.png"
    },
    {
        "SNo":1,
        "State":"Andhra Pradesh",
        "Type":"State University",
        "Yrofestab":1964,
        "Name":"Acharya N.G. Ranga Agricultural University, Lam, Guntur – 522 034,Andhra Pradesh (State University)",
        "Name_1":"Acharya N.G. Ranga Agricultural University",
        "Village ":"Lam",
        "City":"Guntur",
        "District":"Dt. Guntur",
        "PIN":522034,
        "url":"https://angrau.ac.in/",
        "Phone":"0863-2347102",
        "Email":"registrar@angrau.ac.in",
        "location coordinates":18004250430,
        "Image":"https://angrau.ac.in/Images/hmsl1.jpg",
        "Logo":"https://factstranscript.com/wp-content/uploads/2020/07/Acharaya-N.G.Ranga-Agricultural-University.png"
    }
  ];
  
  export const keys = ['SNo', 'State', 'Type', 'Yrofestab', 'Name', 'Village ', 'City', 'District', 'PIN', 'url', 'Phone', 'Email']